### ISSUE TITLE
Use of uninitialized value in concatenation (.) or string

### ISSUE THREAD

**Issue by u238** [WuerthPhoenix/OTRS-DynamicFieldFromDB#1]
-e: Use of uninitialized value in concatenation (.) or string at /opt/otrs/Custom/Kernel/System/DynamicField/Backend/DropdownFromDB.pm line 1010.
 -e: Use of uninitialized value in length at /opt/otrs/Custom/Kernel/System/DynamicField/Backend/DropdownFromDB.pm line 1012.
 -e: Use of uninitialized value in split at /opt/otrs/Custom/Kernel/System/DynamicField/Backend/DropdownFromDB.pm line 860.

**Comment by Patriciozambrano** [comment]
Hello, I am getting the same problem...,  when I try using a dropdown field and check it using the firefox source element, apparently it brings the value of the option but does not show the string value . it just shows blank spaces..

I already tried alot of different things but no success.., 

regards

Using. Otrs 3.1.5 mysql

**Comment by u238** [comment]
This seems not a fatal error, but a minor bug I think.
Probably you must tune your query.

Can you provide me your query?
Remember that the first column specified in the query is ONLY used as "key" in the option tag, while the others in the "value" part. So remember to select always _at least_ two columns, preferring a unique key as first column.
e.g.:
SELECT id, name FROM table

**Comment by Patriciozambrano** [comment]
Hallo

Yup, I am using this syntax , 

SELECT data FROM example_autoincrement WHERE id = 1  (The table is an internal one from otrs which I created), I am not using an external yet because I wanted to see if it worked with an internal first.   (Could this be the issue?)

I am not putting anything on Visualization Query

Thanks
Kind Regards
Cheers

On 03.12.2012, at 16:24, Thomas Forrer wrote:

> This seems not a fatal error, but a minor bug I think.
> Probably you must tune your query.
> 
> Can you provide me your query?
> Remember that the first column specified in the query is ONLY used as "key" in the option tag, while the others in the "value" part. So remember to select always at least two columns, preferring a unique key as first column.
> e.g.:
> SELECT id, name FROM table
> 
> —
> Reply to this email directly or view it on GitHub.

Kind regards,
Patricio Zambrano

---

seyes GmbH
Sophienstr. 21
95444 Bayreuth
Tel.: 0921-78 77 75 - 0
E-Mail: patricio.zambrano@seyes.org

**Comment by Patriciozambrano** [comment]
Helloo

I meant to post the following query, oops..

SELECT id,data FROM example_autoincrement

Regards
Thank you
On 03.12.2012, at 16:24, Thomas Forrer wrote:

> This seems not a fatal error, but a minor bug I think.
> Probably you must tune your query.
> 
> Can you provide me your query?
> Remember that the first column specified in the query is ONLY used as "key" in the option tag, while the others in the "value" part. So remember to select always at least two columns, preferring a unique key as first column.
> e.g.:
> SELECT id, name FROM table
> 
> —
> Reply to this email directly or view it on GitHub.

Kind regards,
Patricio Zambrano

---

seyes GmbH
Sophienstr. 21
95444 Bayreuth
Tel.: 0921-78 77 75 - 0
E-Mail: patricio.zambrano@seyes.org

**Comment by u238** [comment]
Hi,

the query seems to be ok, but you _need_ to specify always the connection string (with username and password), the backend _never falls back_ to the local otrs DB connection if nothing is specified.

regards,
Thomas Forrer

**Comment by Patriciozambrano** [comment]
Hello

Yup, I did specify the username and password on the required fields. But still I am getting the bug. 

Are you also getting the bug?

Regards
Cheers
On 03.12.2012, at 16:37, Thomas Forrer wrote:

> Hi,
> 
> the query seems to be ok, but you need to specify always the connection string (with username and password), the backend never falls back to the local otrs DB connection if nothing is specified.
> 
> regards,
> Thomas Forrer
> 
> —
> Reply to this email directly or view it on GitHub.

Kind regards,
Patricio Zambrano

---

seyes GmbH
Sophienstr. 21
95444 Bayreuth
Tel.: 0921-78 77 75 - 0
E-Mail: patricio.zambrano@seyes.org

**Comment by u238** [comment]
Hi,

Can you provide me your complete configuration?
There must be a misconfiguration, did you try to connect to the database manually with the parameters provided in the settings?

regards

**Comment by Patriciozambrano** [comment]
Hello

Apparently it works now :). 

I removed the javascript that denied change in the parameters field when creating a new dropdowndb dynamic field. 

After activating it , it is now possible to indicate a parameter freely and the contents of the dropdown changes depending on what you indicate when creating a new ticket for example.

Regards
Thanks!
On 04.12.2012, at 13:54, Thomas Forrer wrote:

> Hi,
> 
> Can you provide me your complete configuration?
> There must be a misconfiguration, did you try to connect to the database manually with the parameters provided in the settings?
> 
> regards
> 
> —
> Reply to this email directly or view it on GitHub.

Kind regards,
Patricio Zambrano
