### ISSUE TITLE
Does this work with 3.2.1?

### ISSUE THREAD

**Issue by Ibsol** [WuerthPhoenix/OTRS-DynamicFieldFromDB#2]
Im a noob to OTRS and im trying to create a change request form that has dynamic fields:

eg: Server field <pick as server> from a drop down.

Environment field is then populated with relevant Databases (dependent on what server is chosen)

I cant seem to install this package because i get the following error:

Backend ERROR: OTRS-CGI-10 Perl: 5.8.8 OS: linux Time: Sun Feb 10 14:42:15 2013 Message: Sorry, can't install/upgrade package, because the framework version required by the package (3.1.x;) does not match your Framework (3.2.1)

Is there a way around this?

**Comment by sciolto** [comment]
The plugin is not yet compatible with OTRS 3.2.X
We should be porting it soon to the latest release. 

Greetings
